##########################################################################
# crazy.tcl by ShakE <shake@abv.bg>		                         #
##########################################################################
# Tozi tcl 6te nakara bota vi da prikazva prostotii na private i v 	 #
# kanalite, s koeto napravo podludqva userite :>			 #
##########################################################################
# Ako imate nqkakvi vaprosi, predlojenia ili kritiki posetete foruma na	 #
# http://shake.hit.bg i pi6ete tam!                                      #
##########################################################################

set ransex {
  "sex mex kex"
  "the fucking sex rulez..."
  "Imam Amolet Az"
  "Kur - sonda, koiato, kolkoto i da dalbae, niama da vidi svetlina v tunela i edva li ste stigne danoto."
  "Polov akt - poniakoga, kogato se osastestviavashe na otkrito sastaviaha akt, a sega si e samo fakt."
  "Optimist: Kak da ne jivee s perspektiva, 6tom s kura si opravya vsyaka sliva!"
  "Cenen lubovnik: netakti4en, no pari4en"
  "Minet - seksualen protses, pri koyto majat zapushva ustata na jenata i y otnema vazmojnostta da govori"
  "Glasova dvojka: Po vreme na seks, kre6tyat li kre6tyat! Dva kvartala ot tyah ne mogat da spyat!"
  "Prezervativ - skafandar na kura, koyto vse se oplakva, che go pritiskat otvsiakade"
  "Putka - vertikalen razrez mejdu krakata na jenata.Pri legnalo polojenie razrezat e horizontalen"
  "Viarva6 li v liubovta ot pruv pogled ili triabva da mina pak?"
  "V tialoto ti ima 256 kosti! Ne iska6 li o6te edin? "
  "Ne sum mnogo dobur po matematika, no AZ + Ti ne pravili li 69"
  "Ne sex e otgovorut. Sex e vaprosut. Da e otgovorut"
}

set ranshake {
  "ko za ShakE be...toi lud lud :)"
  "ShakE RuleZz"
  "da go ostavq6 namira toi e moi 4ovek shake-a"
  "ei toz ShakE...ostaite go namira stiga ste mu iskali add, bnc, bot..."
  "vii ShakE mai samo za iskane go tarsite...da va ibe!"
  "mda...moje da te opane analno"
  "heh ko mi prikazva6 za ShakE...toi ibe si4ko deto myrda"
  "JusT ShakE iT :P"
  "ShakE iT BaBy!"
  "nai6 kak klati toq :)"
  "6ti razklati zadnika ei"
  "s pidrazi ne sa zanimava!"
  "dai mu kurviiiiiiiiiiiiiiii"
  "ko ti sega zaribqva6 li go?"
}

set ranhi {
  "Ooooo.... brato"
  "yo man"
  "ejjjjj...sladur...."
  "ei chifyt!!!!"
  "ebati pora"
  "Hi be"
  "zdrasti, kak si?"
  "hello"
  "hi"
  "hey"
  "zdrasti"
  "Hi!"
  "Zdravo!"
  "mda, gepi.."
  "hi"
  "hui"
  "opala"
  "hola!"
  "kvo staa be?"
  "aide be, kyde izchezna? :)"
  ";-)))))"
  " "
  "pa shtom kazvash :)"
  "hey!"
  "maraba!"
  "ihaaa.."
  "hi hi :)"
  "oho :)"
  "aide be :))"
  "dr"
  "bonjorno.."
  ":)"
  "privet :)"
  "bronto.."
  "gepi kopele..."
  "Nenam, obache wchera edin polow atlet mi naprawi gz na woinishko kepe"
  "Egati kwo shte kaja na gadjeto si za razshireniq mi anus i razkusanata putka"
  "Putka maina neorientirana..."
  "dai da obrusnem kosmalaka na taq putka"
  "are da te redime sys teleto"
  "russian vodka rulz"
  "flagman vodka rulz"
  "Mumiy Troll` - Moq pevica.mp3 rulz"
  "Chuh che Kiedis bila mnogo qka kudrawa putka, wqrno li e?"
  "Antler kwo GAYsko porno na DVD ima ne e istina, iSaBeL cqla nosht mu se kefeshe..."
  "STRASTNA^ se pofali che nqma shini weche..."  
  "Taq STRASTNA^ e se edno manekenka na toaletna hartiq" 
  "Are da ebeme dewstweni puteta,a?"
  "Ei shte prebiq kelesh s keleshite...shto si karal koleloto na brat mi?"
  "Q natisni Alt+Ctrl+Del dwa puti mnogo byrzo i mi kaji kakwo shte stane?"  
  "ei termos shte ti sloja ban sha znaish"
  "ot bira samo shnura mi razbira"
  "sokeres tu iu, shokar sym tenk iu"
  "iSaBeL shte uchastwa w borba tejka kategoriq, are sichki w Sportnata Palata da gledame"
  "your biggest fan is my CHLEN"
  "wyrtiii"

  "chushkata e muj kato lajno na dujd"
  "ya ya ya wases mus wases das this is ALiAnS pederaz"
  "wchera edno aishe s nadut stomah tyrsi Hashishev pred Kiroff"
  "kojto nosi bqlo, zdrawo mu se e doebalo"
  "kwo se borish kato prase s tikwa?!?!?!?!"
  "lele male lele male lud kupon nastana"
  "widqhte li nowata stranica http://www.ALiAnS.isgay.com?"
  "Boy, ebane i srubska muzika rulz"
  "Koi e flandera na #bebetata?"
  "Nqkoi znae li de e BuHegouHaTa?"
  "iebem iebem"
  "malkata_jo svalq v1r00sa znaesh li 4e ebafka mn obi4a da i se govori na l:o))"
  "Antler mi se pohvali 4e e dolen GEY"
  "iskam da te shibam baby"
  "abe q Let's the LADYBIRDS fuck all be:o)"
  "ti si mn zle pove4e ot kolkoto o4akvah"
  "q se nadypi iskam da vida neshto"
  "uuuu basi gnusarq si"
  "nevuzmozen si prestani"
  "ae stiga de neti li pisna"
 }

set ranre {
  "re ti"
  "rehi"
  "oho :)"
  "ti si re"
  "reeeeeeklama"
  "re-nde"
  "repichka"
  "ma ne mi rekai"
  "pak li ti be :)))"
  "ne ti li pisna samo da vlizash i da izlizash?"
  "ti se vyrna? ne mozh da byde ;)"
  "aa, doidohme si na dumata :)"
  "hehehe"
  "bre"
  "HEY!"
} 

set ran# {
  "Do not invite in this chanel,because i gonna kick you!"
  "the mother fucker saga continues...pidraz inviter!"
}

set rankvo {
  "neznam kvo"
  "mi kak kvo sharano"
  "you talking to me?"
  "mi kak kakvo iairian s malko ocet"
  "ne me pitai men ne znam"
  "kvo shto kakvo kak kude zashto koga kak po kakuv nachin s koi kogo abe ebimy majkata"
  "kafiava krava"
}

set ran? {
  "?!?"
  "!!!!!!!!!!"
  "!@#!%!%!$^%$&^!^^&#%$$%!$%!@"
}

set rannite {
  "i love you!... ne be shegyvam se"
  "hummmmm, neshto se razsmurde"
  "RYS PEDERAST RYS PEDERAST..."
  "nazdrave za zdraveto na sudiata"
  "Ploska si kato bateria ot 4 volta i polovina (varta - po dobrite baterii)"
  "ei ti!! "
  "spodelete..."
  "Kvo iadesh kiyftetata kato semki bre a puk vaflite napreko? posle malka ti bila ystata!!"
  "Ej niakoi da znae dneshnata parola na FBI"
  "Izvinete kolko e chasa"
  "Grehska Greshka oburkah vratata(jenata)[rukata]"
  "AAAAAAAAAAA izcepi se nepodgotven"
  "peresh???"
  "BRUM BRUM vrrrrrrrrrrrrrrrrrrrrr"
  "dzidzibidzi ala bala tzur pur STARIA BEN"
  "nao dzedyn"
  "Pich_ot_klasa^: zashto ochite sa tolkova krasivi zashto kosata ti e tolkova nasrana..."
  "Tezi kraka koito sa tolkova hybavi tezi ochi kato kokosovi orehi tazi gladka koza tozi dulug hybav...  no stiga tolkova sme govorili za men kazi neshto za teb"
  "Tih vetrec mi vee slabinite, struk treva me bocka po guza, kleknal neide iz poleto tihichko sera - sera, guza s lista nakichki nasranoto da ne lichi"
  "************************************************************************************* - kvo se pylish be sniag vali..."
  "ti si gaden i mazen chikidjiq"
  "date shibat 300-ta potni negri"
  "100+200=300 na gyzati ima pista a az sm motorista"
  "zashto imash kosmi m/y prustite be"
  "grozen si kato pleshiva qrebica"
  "da duhash taratora be nestasnik"
  "smurdish kato na durt por zadnika"
  "tup si kato na maiski brumbar zadnika"
  "kvo zqpash be gyz"
  "tup si kato maimunski zadnik"
  "dai dai vurti aide na kiu4eka su4i vurti obarni"
  "abe ti si mn tup, ne maikati e tupa 4e te e rodila"
  "ti 4upa glavata be naesh li kva bata imam samo"
  "zadnika ti e debel kato boiler be bidon razpliokan"
  "pederast gur4av"
  "ti si visok snazen i PROST"
  "*** Your nick is now PEDERAST"
  "brao be dokade stigna dneshnata mladesh nie vie sram"
  "Muhal!"
  "Prost,kato magdanoz;tup , kato slonski pup; dif kato koralof rift"
  "ti puk se izhvurli kato chikia na mokur pqsuk"
  "Vie negramotni li ste ili ste tapi po rozdeni?"
  "imash refleksite na ymralq kotkata opashkata"
  "Xe-xe vushkite ti mai pak za zaformili kupon a?"
  "dati go ftukne slon pod naklon sus zasilka ot balkon"
  "uaaa pisna mi ot teb nevuzmozen si"
  "zasluzavash da hva i dati otkusna topkite i da si gi naprava n gerdan she mi stoi cool mislq"
  "bezobrazie!"
  "abe boli te faro moze i miga4o"
  "se v gyz i se v moq mama my da eba"
  "ymri kato mastiq"
  "SEX na EX prava sqka zaran SEX na EX"
  "ako neznaesh kak se pravat grozni deca prosto popitai maika si!"
  "4ekai malko sa"
  "tolko si mrusen i 4eren i gnusen 4e se slivash s asfalta"
  "abe...ti mai si onia ot resia koito mi zadigna kepeto"
  "krivopishkov 4ikiboec"
  "xaxaxaxa skrii si malkata pishka be rasmivash me"
  "ako iskash bezplatni yslugi zvani na 952 05 34 sled 9 chasa pls"
  "ako tqloti ti beshe proporcionalno na mozakati sheshe da se poberesh v orexova 4erupka"
  "kogato govora s teb s edno govora s guzati"
  "undale undale qriba qriba ua ua "
  "AZ SM IDIOT!!!"
  "kvo prezarvativi polzvash az sm s VITALIS mn sa zdravi"
  "dati izgniqt 4ervata"
  "ti si shibano kopele"
  "mrusen izvraten gey!!!"
  "ti si abe ...... aide dane zadalbavam tazi tema!"
  "ti si kyh kato 100=to gradinski leiki"
  "ti znaeshe li 4e maikati e gaden negar"
  "ti si bolkuk "
  "neiskam da govora pove4e s teb pod dostoinstvoto mi e"
  "iskam te na zadna prashka"
  "dami go ligavish"
  "tup kato galosh si"
  "AZ AKO BQH NA MQSTOTO NA MAIKITI DASM TE HVARLIL OT NQKOI MOST BE!!!!"
  "smurdat ti krakata bratle"
  "uuu tazi mirizma dane idva ot 4orapiteti"
  "az sm angel4e a ti si dqvol4e"
  "shete klata kato gladen ciganin gjanka be:o)"
  "Tup si kato manastirska gygytka xixixxixixi:o)))"
  "Xey bambino ke me hvanesh za marky4o q kete baram po ciconeto"
  "ae odi beri gybi be"
  "sladur imash ysmifka na s4ypena mifka"
  "abe ystata ti e 4ervena kato maimynski zadnik xex:o)"
  "aide ela v nas da gledame XXL i da probvame razli4ni pozi"
  "ae sa kvo mi se praish be..."
  "CSKA COOL CONDOMS:o)))"
  "ako 4etesh sa tva ti si pulen idiot!!!!"
  "abe kvo mi se vrazvash nese spi4ai"
  "dati go nataralqnkam v dypeto be gotin pedal"
  "abe pedro sho nekazvash 4e si gey"
  "egate triper tresne besniko besen"
  "kyh si kato dypkata na gewrek:o)"
  "w0w qko me divish syper pi4e si"
  "ihaaa kakvo dupe vadish samo lele kakvi misli mi idvat...."
  "abe razpraat che ebafka e golqqma fenka..verno li e?:o)"
  "Keep on Rollin baby Rollin Rollin Rollin"
  "q trai 4e nesi si mil ystata ot meseci nemi se ymira mlad!!"
  "iskam da ieba si4ki FENKI FENKI"
  "shhh brato pusni si LimB Bzikvitkite i si karai kupona"
  "ae na kupon v nas koito iska da izvika DAAAAA!!!!!"
  "maikati e durta pa4avraa beeee"
  "hah kakvo suvpadenie"
  "dnes na moda e da si mobilen i s malka pishka kato teb"
  "q mi podai havliqta otivam da si zema dush ako iskash ela mi natarkai garba:o)"
  "slushal li si K|\aTu stlashna pevica e ama neshto ezika i pre4i"
  "abe verno li e tva 4e KaTu mozesh da q opravish sreshty 500 marki"
  "IRC SUX IRC SUX IRC SUX"
  "iskam da eba edKo edKo na zadna prashka da iskarta negovoto dype:o)))"
  "zashto o4iteti za tolkoz krivi ....."
  "yeah WHERE ARE YOU uuu u uu u uu u uu u u"
  "tup tup tup tup tup tup tup tup tup tup tup tup tup tup tup tup BEEEP"
  "shu shu shu zashto se skrihme dvama ot dazda v tezi gadni hrasti"
  "nai obi4am ludi ludi zabi na sun..."
  "ot tva tupc tupc glavata mi po4na sama da tupca"
  "ieeeeeeeea niiismie ot dalieko i govolieme na mieko"
  "abe znaesh li kolko me boli fara kvo praish sa"
  "offf pisna mi date gledam ae boom bamm i da te nema"
  "ti dane si mangal4e mn si 4eren"
  "4 R D zelaqti si4ko nai nai..! s mn obi4: mama"
  "dnes ti she 4erpish si4ki v kanala"
  "ae y vas na po 4ashka vince s kisali krastavi4ki, domatki i sushenica:o)"
  "eeeeeee naliti kazah da vnimavash dane se napiesh s taq mineralna voda"
  "probvai da se napiesh s mineralna voda posle glavata nete boli garantiram"
  "naahhh"
  "be ia se vizh na kvo prilichash!"
  "dobre de.. po-leko"
  "ok, sedi mirno"
  "bam nichibun!"
  "ti mi pregyna samochuvstvieto be!"
  "i eto idwa nai shtasliwia denn.. kogato ...ti.riri ram :)"
  "kakvo ti stava be?"
  "dobre li si?"
  "otkyde se prykna be izchadie na 9tia krug"
  "ti mai zabravi da mi kazhesh hi"
  "?"
  "!"
  "..."
  "tri plius tri ravno na devet.. shes po shes ravno na mercedes!"
  "ne mi se govori po takyv elementaren nachin"
  "ako se zamisliash nad moite dumi shte me razberesh!"
  "ne ne ne!"
  "da da?"
  "po-dobre da doidat tankovete..!"
  "v takiva sluchai se vika 'Dal bog na fugi dyrvoto' :>"
  "ti nishto ne razbirash ot mnogosmisleni razgovori"
  "mai ne mozhesh me razbra a, da ne si blondinka?"
  "az ti predlagam neshto.. ti otsiavai"
  "heh..da..ma neshto sum i ill..iawno"
  "gledash 5 min w grushkata na lampata i she widish posle .."
  "heh..brawos:)"
  "ti ne beshe li away predi malko?"
  "metalika sux btw"
  "koi ti kaza?"
  "ti si ot novoto pokolenie mai"
  "heh, razbirko.. niama shto"
  "alo, slynce zashto ne mi govorish?"
  "ti mai ne me obichash veche :<< "
  "au she placha"
  "brb malko da si otvoria paket cigari"
  "a neska kak se napushih.. tva tvoito nishto ne e.. oshte me dyrzhi.. za tva malko taka govora.. "
  "fuck you! bed off with you..."
  "vizh kolko e krasivo nebeto dnes"
  "ti si velik, you RULE.. you sick! :->"
  "a moa li da ti vkaram edna?"
  "odi beri krushi be"
  "ma ne mi govori taka samo!"
  "ti se mislish za vyrhyt.. ne moga da poviarvam.."
  "Slackware RuLeZ Forever"
  "abe ti na kolko si godini?"
  "mlad sam oshte za takiva neshta"
  "v uchilishte.."
  "NAZDRAVE ..."
  "znaesh li, mnogo stranni neshta chuvam ot teb dnes"
  "tvoia stil mi e poznat, da ne si bg chado?"
  "q trai"
  "debilno, debilno.."
  "typo.. ta drynka :>"
  "iskam da sme samo ti i az, inache ne e romantichno"
  "probvai niakoi pyt da seresh s gyza nagore"
  "shte byde 28 chasa, 97 minuti i 80 sekundi.. din!"
  "az mozh da sym typ bot ama pak sym poveche ot tebe"
  "tva da ne ti e mandra?"
  "shit"
  "dont speak"
  "ti si dyrvo"
  "haha, vizh se be"
  "da"
  "ne"
  "ne mislia"
  "komu e nuzhno?"
  "e ne mozhe sichko da e shes.. heaven must wait"
  "slushai korn za da ne te boli gyza!"
  "Arbeit macht frei!"
  "Ich liebe dich"
  "so what?"
  "aa ne, niaa da ti mine nomera!"
  "samo tva li mozh da ti rodi bezformenata tikva?"
  "are stiga de!"
  "prestani molia te!"
  "greshka!"
  "chai da si premesta patkata ot edinia krachol v drugia.."
  "niamam vreme sega.."
  "be ti ot klinika za narkomani li idvash?"
  "mislish li che she mi otiva chervena kosa?"
  "az si iskam Eva Hercigova.. za drugoto ne znam"
  "mlyk be putko zaspala!"
  "stiga s tia typotiiiiiiiii!"
  "imam ti telefona da znaesh!"
  "vizhdam che iskash neshto, no kakvo celish?"
  "kakvo izpi dnes che taka ti razmyti glavata!?"
  "iskam da mi dadesh ton za pesen... raz-dva-tri-chetyri.. !"
  "your mind - it is the center of your life, it is everything you are!"
  "xuxuxuxuxuxu"
  "nemoga"
  "neznam"
  "iskam da te pitam neshto, mozhe li?"
  "kazah li ti che veche ima topla voda v studentski grad?"
  "be stiga prostotii, dai da si minem na dumata"
  "ia stoi taka da te pitam - kolko struva 1 minuta razgovor ot bg do usa?"
  "abe znaesh li kyv den e 31 septemvri?"
  "zelenchuci koito ne qde, ui golqm ne shte mu poraste..."
  "be ne mi se ligavi molia ti se.. kvo se izlagash sa.."
  "a?"
  "away sym, za bonbonki!"
  "da mi stiskash bibitkata!"
  "ti mai ne vizhdash po-daleche ot nosa si :>"
  "az s greshnici ne razgovariam!"
  "drisnia"
  "ti neshto se speche mai?"
  "lele"
  "ops"
  "lipsvash mi!"
  "mrazia te!"
  "ne se disha ot tebe!!!"
  "putka maina neorientirana"
  "dano ne ti se nalaga poveche da pravish tova.."
  "vsichki imat praznik, den e za razvrat.."
  "mnou mi e kef, da znaesh.."
  "shto taka be?"
  "zashto ne mi se obavdash?"
  "i men me zabrawqsh znachi?:("
  "10x:("
  "telefona mi e (046) 43196 Diliana se kazwam, obadi mi se da goworim"
  "a ne ama da!"
  "a az se chudq tuk s koj da si goworq:("
  "izsra li wsichkata hrana deto pogyla na wryshtane ?"
  "kade se namirashe ./named ??"
  "Your ambition will pay off in various ways"
  "You are going to do something soon which is totally out of character, but positive"
  "Your valentine has given you candy and you will choke on it and die.."
  "basi kak da proverq dali bachka sounda na linuxa deba !?!?"
  "aaaaaa kopele toja nick me kefi max :)"
  "You have been marked as being away"
  "nekva kuchka"
  "ti koi si be?"
  "so i dub thee unforgiven.."
  "on a cold october morning, excrossly on the ground.. waiting to make my move and make no sound.."
  "po-dobre da si namera niakoia rusa..."
  "da, ama e:> kak e sled burnite noshti?"
  "mi  chakai samo da si wzema disketata:)"
  ":) t'va pyk otde ti hrumna (udarenieto na !a! ) :)"
  "e kak da ti govoria kato nishto ne chuvam ... sigurno vryzkata e losha ;))"
  "ti ne beshe li v subota na baba yaga?"
  "bria tuka polowinata sa prez bia-bg ili .edu :))))"
  "Az se qdosvam shtoto CSKA padnaha ot teq kuci pileta !"
  "cheti...private -to :)"
  "oooo, hi"
  "hm, mi s cherna kosa sum"
  "hvani kum MM i zastreliai vodeshtata i onia tupaci v studioto"
  "hahaha tukmo si pomislih che si rusa:P"
  "Pochvam da se chustvam kato oligavena vyzglavnica :)"
  "podkarwal li si sniffit pod solaris 2.7 ? :>"
  "Woohaa Woohaa"
  "i dont give a shit"
  "kude sha ma vodish?"
  "I'll be waiting.."
  "lesno ... s trenirovki i upraznenia"
  "nemoga da te gledam !:P"
  "hey playboy kak si?? :)]"
  "NE MOGA DA VI DISHAM VSICHKITE"
  "naesh kvo? probvai da polzvash samobrysnachka vmestu toaletna hartia.. udobno e .. samo posle dobre da ia izmivash.."
  "che az da ne sum niakoia seksapilna friziorka be ???? begaj nekude da te obrusnat"
  "da ne si sabirash zubite sas schupeni prysti!"
  "vodi normalen polov zhivot !:)"
  "AZ SYM NA 180 GODINI"
  "abe znaesh kak e!"
  "male k'vi glupavi hora imalo"
  "...che i-neta e vreden , che nemozhel da zameni knigite , che bil vreden za uchite"
  "kak si be termos?"
  "shte mi svish na trompeta"
  "-ÄÄ [netsplit] (irc.nyTka.net/irc.kyp.com)"
  "kakvo ste reche tva?"
  ".. kurwi ima tuka zad poshtata po towa wreme :-))))"
  "propusnah da te celuna"
  "Vikni si edna PROSTITUTKA be!!!!!!!!!!!!!!!!!! Az sum kurwa"
  "e .. az si mislih che zadnik s pryt"
  "say it again"
  "stiaaa be .... she se naseraaaaaaa a... are chao vi"
  "tuka li si be moi chovek?"
  "az wsichko znam :)))"
  "10x"
  "10q"
  "deset hiks"
  "bananche za mene, bananche za tebe.."
  "lick it up!"
  "koi si ti be kompleksar?"
  "kak sa seti ?"
  "nikoga ne planuvai neshto predvaritelno!"
  "ti ne beshe li edna rusa?"
  "sluncho :)"
  "salatata e tuka a ako terazbera koi si samo na salata she mi stanesh!!"
  "znachi taka move da wzimash drugi hora na kupon a mene ne, taka li?"
  "abe ti zashto gledash snimkite na lucy be?"
  "i don't see any shit"
  "ok who left the pile of shit in the channel?"
  "shit? where is it? so noone steps in it!!!"
  "i hope you wiped your ass :)"
  "well flush it!!"
  "ok who farted?"
  "cow shit, horse shit, dog shit, cat shit. what kind of shit is it?"
  "gepi ma za pechurkata!"
  "tyi reche zaratustra..."
  "i az kvo da napraa? si udara gyza v tavana?"
  "kvi-kvi"
  "za poreden pyt se izkaza :>"
  "ama ti si niamash rozovi kilimcheta v kenefa!!!"
  "da mi merishesh minzuhara!-)"
  "kvo mi se praish na 3 i polvina be?"
  "be ne beshe za tebe tva, kvo se obazhdash?"
  "v momenta pia bira, ne vizhdash li?"
  "eh pile, koga she se nauchish che krushata ne pada po-daleche ot darvoto..mojesh li da tarsish pod krusha qbalki a?"
  "be tebe da ne sa te ebali ludite?"
  "da ti gu turi slon pod naklon sys zasilka ot balkon na bul. bykston!"
  "vsichki samo prostotii znaete.. ama kat se opre do piene i kyde ste a?"
  "ludostta bila zarazna"
  "skromno :>"
  "ba li go?"
  "stia s tea piramidi faraoni be, dai praim pachki!"
  "problemi li imash?"
  "ako iskash moga da ti dam toaletna hartia da se uspokoish malko"
  "az she vikna tia ot hei i she im kazha kvi gi byrkash nezakonni i she vidish ti!"
  "niaa takiva filmi"
  "ama ti verno li?"
  "toziiiiiiiiiiii raaaaaaaaaaaai vodi v aaaaaaaaaada.."
  "smeni povedenieto ili she vidish irc prez kriv makaron"
  "nein!"
  "was?"
  "iskam te!"
  "iskam da mi padnesh na kanapeto v hola, ili da te ... v kilera na tymno .. "
  "ne sym umrial sha znaish.. za tvoita sliva mirizliva .. sha znaish!"
  "ebah ti maikata kirliva.. sys moita krastavicka kriva"
  "abe ia cat /dev/shit > ./tvoita usta!"
  "fuck the shut up!"
  "uuuuuuuu"
  "eeeeeeeeeeeeeeeeeeeeeeeeeeeee"
  "ami..."
  "neska gleda li se v ogledaloto?"
  "grrrrrrrrr"
  "ela da mi vidish huia na zhivo!"
  "tebe mai skoro ne sa ti pravili klizma?"
  "imash li pompichka? iskam da si napompam gyza i da ti se izpyrda moshtno v chovkata!"
  "odi iazh kompot"
  "be otidi se chukai s demond, ne mi prikazvai, ne moa ta traia!"
  "she kazha na sodo da te uhape!"
  "ah, da niamashe v teb takava prostota, shteshe da e chudna nashata igra!"
  "ti li she mi kazhesh!?"
  "ama kazhi si kvoto mislish za mene, kvo.. sram li te e?"
  "celuni me!"
  "zadnika ti mozhe li da kazva 'Aaaaaaa' ?"
  "marsh be, merishat ti krakata!"
  "tva zvuchi gordo"
  "iad li te e?"
  "stegni se de, kvo se speche :>"
  "stava interesno"
  "licemer!"
  "v detskata si vyzrast znaeshe li che ot tebe she izleze takava utrepka?"
  "ku ta kovna s teslata samo na mastul she mi stanesh.."
  "ma ne me mastulosvai be"
  "ia ne govori tolkova ednosrichno che stava banalna cialata istoria"
  "az se prerodih"
  "heh, kalyf!"
  "abe da znaesh sluchaino kolko e golqma cernata dupka w linsuxa? sta prata taam da znaeh ... mv klamer /dev/null"
  "iskam da te chukam v cyfnalata ryzh.. ili neshto takova :>"
  "tolkova li samo znaesh?"
  "iskam zadnika ti uhilen do Ushi... i da go natypcha s krUshi :>"
  "znaesh li che vengador mnogo ti e nabral?"
  "brb"
  "ama tuka niama domati, tva e knizharnica!"
  "meh, leke silistrensko.."
  "byllllllvoch.. pumia.. blia.. ueeeeeeeeeee.. "
  "û9 = 3 :>"
  "taka, taka.."
  "i posle?"
  "fantazirai si.. :>>>>"
  "                                      .        "
  "ne taka, ako obichash!"
  "ur welcome"
  "abe .. zhivei nebrezhno dokato umrat sysedite! pa kato umrat she te pokanat na pogrebenie i pak she piesh !!!"
  "da te chumata iade!"
  "mastika forever!"
  "ih, chak me zasyrbiaha testisite.."
  "mda"
  ".. i shte ti go podam tvyrd"
  "miaaaaaaaaaaaaaaaaaaaaaaaaaaaooooooooooouuuuuuuuuuuuu"
  "eeeeeee tva ti li si be, bassi ne moa te poznaia!"
  "slusham!"
  "po-leko da ne lapnesh na fugi dyrvoto.."
  "tova ne me zasiaga"
  "i love my lame ass!"
  "za tebe sichko mi e ot iasno po-iasno be, nali ti chetoh dosieto.."
  "ti za kvo mislish che toaletnata hartia e dvuplastova? nali edinia plast ti otiva direktno v dosieto"
  "narichai me mastulien... obicham francia, parizh.. frenska liubov.. btw iskash mi teglish edna svirka?"
  "eh, da mozheshe da te chue chichko Lenin.. shteshe da se zavyrti v groba!"
  "ee, nedei se pritesnqva be.. ti ot maitap ne razbirash li?"
  "pusni si CNN byrzo! davat arestuvaneto na demond!"
  "zhalka utrepka.."
  "kazhi be bokluk!?"
  "ti seriozno li po cial den na irc visish? maikaaaaa.. triaa si s mnoo komplexi znachi.."
  "oranzhevite maiki s oranzhevi dechica..."
  "az sym samo edin iunusha beden.."
  "iskash li da ti kazha edna publichna taina? ti si seksualen invalid.."
  "baaaaaaaaa, she mi opadat kosmite ot gyza oshte malko ako te slusham!"
  "niama znachenie.."
  "i?"
  "((-:"
  "ne dyrpai diavola za opashkata che toku vizh ti se izsral otgore... e togava ne ti zavizhdam naistina .. :>"
  "lemur"
  "vizhdam li kolebanie v ochite ti ili taka mi se struva?"
  "ibi my kopili ibi my, shot sym lekomislina.."
  "qm i piq, iby i biq"
  "rozovoto ili sinioto?"
  "abe bira sex i CSKA!"
  "tc tc.. zavi mi se sviat na svetofara!"
  "dreme mi na pumpala"
  "az mastul li sum ili uiova glava?"
  "mm.. ia ela da mi pokarash trotinetkata!"
  "biva li taka?"
  "ne e tva tochnata duma spored men"
  "imash li snimka?"
  "shut your mouth!"
  "mnogo sladkodumno govorish, chak bybreci me zaboliaha.."
  "po-zdrav za tebe po fm+"
  "te has mi kola"
  "hoi pitai katil ;-)"
  "o`ti n`eba putkata maina"
  "mm.. tiiii... dovechera kak si s vremeto?"
  "are stiga zadava typi vyprosi!"
  "ti mene za typak li me mislish?"
  "aaa-se-ga-o-ba-de-ni-q-na-molq-drugar-ka-taaaaaa"
  "nachi zavivash naliavo, otivash do edna niska sgrada, stigash do sinia vrata, natiskash edno sluginche, pokazva se edno butonche i vikash dai dve milicionercheta za chicho banichko"
  "dai da zamesime nekoi ot kanala.."
  "chu li nai-novia sluh za lanzz?"
  "be neshto mai ne sym na kef neska ..."
  "shto ne minesh da piem po kafe s raiber"
  "ai da pushim po cigara i posle pak she govorim, ok?"
  "abe ti s windows li si?"
  "vnimavai sha kaja da te prouchat tebe az sti kaja na tebe.."
  "tuka ima .. tuka nema .. ? kyde e topcheto"
  "ako nekoi ti se struva pros - ne govori s nego"
  "vizh kvo, ako prodylzhavash da mi govorish she te slozha na ignore"
  "ia se pogledni kak smyrdish, tva da ne e opit za plagiatstvo - mastul -> smyrdul?"
  "ku iskash da ubiesh pylkovodeca - ubii pyrvo konq mu"
  "abe vie se smeete i nie se smeeme ama nakraq she si smenime rolite.."
  "koito kol ostri na drug mu vliza v gz"
  "i glupakyt e umen kogato mylchi"
  "po-dobre prelystena i izostavena, otkolkoto zapochnata i nedovyrshena :)"
  "btw naesh che davat 4 muri na cenata na 3?"
  "ne .. s tva e kofti.. chai she mislime neshto prosto..."
  "spokoino be.. ne byrzame :))"
  "aaa .. kak beshe ..."
  "aaaaaaa .. neshto noo si lagnat mai?"
  "ia pitai nekoi ima li da mi dade ena cigara"
  "ogynche?"
  "ei neska me globiha v tramvaia deba.."
  "d`eba vash`ta mama!!!"
  "i ti li she me biesh kato demond i kirov?"
  "q trai da ne te floodna.. che she isfyrchish kat izpyrdqna tapa iz gyz"
  "hahahahaa... .mnoo smeshno.."
  "bleep"
  "happhaite phaphli"
  "shto ne mi smuchesh lukankata .. "
  "when tha shit goes down ... "
  "i will fly to the moon and back if you`ll be my babe.."
  "ne mislish li che e vreme da si lqgash veche a?"
  "nqkoi ima li chasovnik?"
  "hmm, tva oste ne bqh go chuval"
  "ping meeeeeeee!!!"
  "ako iskash tel. 760725 obadi mi se utre sled obqd:))"
  "ma ti kvo, da ne me svalqsh a?"
  "q da si haresam nakoq ot kanala da si lafime.. kazhi .. znaesh li niakoia zdrava putka?"
  "mlaad pozharnikaaaaaar... - tva znaesh li otkyde e? :-)()"
  "aaaaaaaaaah... crushhhhh..."
  "ih ma sym typ nali :))))"
  "da ti go nachukam :)"
  "eh sine sine ... "
  "ma ti izleze li ot bolnicata?"
  "da beshe sipal po edno whisky veche a?"
  "da be, setih se :)))"
  "who are you?"
  "da be.. problema na zhenite ot FMI ne e che sa grozni, a che na 2rata godina pochvash da gi haresvash"
  "kvo mi bibikash samo kato kutrovski be :)"
  "37 08 43 - e tva pa e telefona na b|tch ili se|ena ili bibi|ate ili nekvi takiva se smotani nickove :)) ani se kazva .."
  "iskam da ima marshrutka ot razsadnika do zhe.ka. borovo :)"
  "q kazhi oshte neshto da se seta be"
  "abe skii na kanala se napylnilo s novi pichki .. dai da hoim gi zabivame tokuvizh sme maznali malko da poibem.."
  "vashte znaiat li za cigarite?"
  "if ($hozt !~ /[0-9]+\.[0-9]+\.[0-9]+\.[0-9]+/)  i blabla ... "
  "glupostta nikoga ne svyrshva dotuk unless defined($dotuk) :)))"
  "oh tia dvete Gabby i ophellie kak she gi shibam leleiiii.. kato zverove she se ebeme ti kazvam"
  "eiiiii plashim se kopele!"
  "nee istina .. "
  ".. razbirash li .."
  "balo si maikata"
  "ili taa jazzgril li beshe .. jazzkuchka li beshe kotka li beshe.. ih da mi padneeeeeeeii.. she i skysam trytkata .."
  "ma taa plondi nema nikvi ... deba :))))"
  "a skii lorena-morena... niama i neia koi da ia oprai .. pak az she triaa si prezhalia blagoslovenoto dyrvo"
  "ako uspeesh da si navresh cheshmata v gz pusni toplata voda i slushai jamiroquai .. tva mu se vika 'direct clisma'"
  "ti li si sledvashtia be? :)) hehe"
  "blah.. ot tebe i ot tia skateri she se izdraifam kato valentin v krychmata.."
  "be ti prilichash na lucy be .. nishto ne ti se chete .. i tia taka .. hodi i gruhti .."
  "moe si govorish kvoto iskash, ma az se imam za edin ot nai-pechenite botove tuka, gz si zalagam!"
  "ma kvo mi se kefish kato ciganche v taxi?"
  "lelee, ako te fana shte raznasqm kato praskachka iz loze..."
  "vnimavai che she go otnesesh kato premraznalo ciganche - vatenka"
  "mozhe i veche da ne e aktualno ama edno vreme (po babino vreme, na taia syshtata baba deto goneshe fashistite s tvoite  lafove) takiva kato tebe gi zatvariaha po tvu-ta i zatvori.. aa maha"
  "abe ti ako slushash fugi she vlezesh v zatvora, a ako slushash pianist - nqma da izlezesh ot tam:)"
  "she piinesh li edno kafence?"
  "znesh li , snosti te synuvah ...kak dvamata s tebe...nali razbirash....si lizahme shkembetata i si byrkahme v dupetata..."
  "iskashe mi se da te vidq kolko struvash na zhivo..."
  "ama niama otyrvane ot mene a? :)))"
  "twojta mama d`eba :))"
  "skiwash li - i w kazarmata ne me shtat... e twa e :))"
  "ela nasam, molq!"
  "mi izduhai go be :)"
  "kazhi na onaia zaspa za sreshtata"
  "mi pomoli niakoi drug da go izduha togaa che men me mrzi :)"
  "kazhi muuuuuuuuuuu"
  "she hodataistvam za teb pred ó¿±¸¿²Ñ ½á©¡««»°áó¿²Ñ½¿"
  "ako edin chowek ima dwa e-maila, kak da ti gi razdelq?"
  "mozhesh li da se celuvash sys zatvoreni ochi?"
  "a mozhesh li da seresh s vyrzani ochi? :)"
  "az ne piq be "
  "fanah te da lyzhesh! fanah teeee!"
  "aa.. zadryzh si go.. az ne sym alchen :))))"
  "trqbwa da se pusne poredniq bulk...."
  "e ubu de :))))))) razbrahme che si pedal :))))))"
  "biraaa! biraaa! what has become of you?"
  "nali ti kazah che dnes sym v zatymnenie"
  "ooo slyncho :))))))"
  "obich moia!"
  "oooooooonnlllllllyyyyyy yyyyyyyyyooooouuuuuuuuuuuuuu.........."
  "ne me kefish be"
  "naesh kva e razlikata mezhdu gospod i DJ-a? :))"
  "da be :) koito tyrsi namira .. taka kazvat pone.. i koito sere sichko Usira :))"
  "'bal sym i PCtata 'bal sym i chudoto :)"
  "mjetnesh kurosh naramosh .. pojebesh pobjegnesh.."
  "Trista Liudmili v gyzy ti!!!"
  "'640K sought to be enough for anybody.' - Bill Gates, 1981"
  "shveps rulez .. i pecheni zhenski zadnici na sredizemnomorsko slynce :)))"
  "baba ti rulez :)))"
  "nali s bratofchet ti pederaza ne q obichahte mnoo-mnoo ;]"
  "eh predstavqm si vi kak se greete edin-drug ;]"
  "pozhe li da te pipna po dupeto?"
  "iskam da te stisna mezhdu krakata :)))"
  "az sym pederas, ama i ti ne padash po-dolu ot mene :)"
  ".. mi taka ili inache sym liubimeca na vsichki :))))))))))) shto da ne si praa i az malko avtochetki :))"
  "ebati sa perverzii ne moa se seta ama taka kat te gledam bih naprail neshto za ovlazhniavaneto na ekrana si :))"
  "tolkova li sym prost i cinichen?"
  "az pa ne sym takyv komplexar kato tebe :)"
  "baaaaaaaaa, she mi opadat kosmite ot gyza oshte malko ako te slusham"
  "nali she mi oblijesh gz?"
  "nema da ti go wkaram celia....samo do makarite"
  "ako mi raboteshe dcc-to shtiah da ti prata moia snimka po bikini da vidish kak mi visat kambankite otstrani.."
  "qj mura da ti raste kura"
  "Aide na vlechkata i da se syrkame..."
  "Kleptomaniata e sposobnost da namerish neshto predi niakoi da go e izgybil"
  "Kolezke sreden zadovoliava li?"
  "Koga chy tova Mokanina tytaksi my se povdigna neshto...  i taia mi pisa 3 na prerazkaza..."
  "prdajbi na edro i siiitnoooo"
  "hemoroidite sa golemi gazari"
  "takuv shte ti svetna che shte ygasnesh"
  "Kakvo si se otpysnal kato syh parcal na morsko duno.."
  "Magazina se premesti ot APK sreshty SBA"
  "Zashtoto nestandartni smieeeeeeeeeee"
  "Nemoga da si pribera zubite ot smiah..."
  "sedem puti meri,edin put othapi"
  "lakomo dype, kruv SERE"
  "po-dobre da padnesh dyhom,otkolkoto da dyhash padnal!!!"
  "sedem puti meri,edin put glutni"
  "i SHAT na patkata glavata!!!"
  "Oilaripiiiiiiiiiiiiiiiii....."
  "ZAETO!"
  "BEGOM OT MEN DO DRYGOTO DURVO"
  "Varosaite bordiyra cherno"
  "ebi me zdrawo kurwoooo"
  "ei shte te otnesa kato premruznal ziganin watenka"
  "gleda li pornoto wchera po TV1000?"
  "e wij sega, chowek se uchi ot greshkite si... she te dropna edin-dwa pyti i poweche niama da se zaiajdash s men"
  "taq komanda deltree /y *.* znaete li q, ako ne q probwaite kato mene"
  "teleto e dwoino po-debela w gza ot ramenete"
  "NOKIA 3210 rulira"
  "gza na SEXY_SLAVA rulira momcheta"
  "YAMAHA MINT 50 rulira"
  "kaji koga shte te wozq na moq scooter between krakata mi?"
  "ZABRANENO ZA LICA POD 18 GODINI! (asl?)"
  "znae6 li 4e razlikata m/u NOKIA i BTK e savsem malka... NOKIA->Connecting People .... BTK->Disconnecting people!"
  "e i az kvo da napravq...moje da te mu6na analno ako iska6"
  "vsqkvi lameri sam vijdal ...ama 4ak takiva kat tebe ne bqh vijdal!"
  "ama to biva biva lamer6tina ama pak 4ak tolkova"
  "ako iska6 vlez v kanal #2,000 ...mnogo e qk da znae6! Ima add za vsi4ki...a na vsi4koto otgore ima super mnogo hora...pove4eto ot koito sa admins&opers na UniBG...ama ti nedei sa pritesnqva!"
  "kva svirka bre lamzo :)"
  "kogo psuva6 ti bre...kato prikazva6 samo laina izlizat ot ustata ti"
  "nqmam pic i ne me tarsi za prostotii"
  "zatvori si ustata 4e miri6e be"
  "koe go biva...maika ti ili pak ne6to nesam razbral?"
  "abe ti napravo s kofite tragva6 bre"
  "te doni i momchil se razpadnali .. shtot vryzkata im se gradqla samo na sex-a zemi si izvadi pouka ..."
  "ama az ne sam mnogo prost...:) az sam malko prost"
  "VERSION"
  "PING 1017404154"
  "ei pute 6a ta skasam"
  "shta skasam v gaza be selqndur"
  "oooooooohhhhhhhh baby 6ti skasam dupenceto...oohh ohhh"
  "abe q 4ekai malko 4e kura mi se izgubi v na maika ti debeloto 4ervo"
  "kva svirka be 4o4i"
  "kaji beb4e"
  "abe nema svirki tuka....samo ti na mene"
  "na maika ti analnoto prasten4e"
  "ako iska6 moje da ti preveda dumata fuck li4no"
  "kva muzika obi4a6 da slu6a6 dokato te 4ukat?"
  "nema da ti pravq svirka..6toto si grozen!"
  "ami svir4ok stava li?"
  "ako si tolkoz prost kolkoto si mislq...pi6i /run rundll user.exe,exitwindows"
  "6te te 4ukam po sistemata 4-4-2"
  "xaxaxaxaxaxaxaXaxAxaxaxaxaxaAxaaxa"
  "/quit az sam lamer!"
  "ok sam bre lameeeeeeeeeeeeeeeeeroooooooooooooooiiiiiiiiiiidddddddddeeeeeeeeeeeeeee"
  "kaji we amsalak"
  "o ti sega li razbra"
  "da ama na maikati tragvam s kofite"
  "stava ama da ne sqdash na nego"
  "a we kalitko"
  "ti si alkoholiziran lamer"
  "da go turq na maikati putkata"
  "ne we kalaf takav"
  "da we ti hermFRODIT"
  "i az teb ama nemoga da te vidq da ti go kaja"
  "a selqk"
  "da kolkoto na maikati analnoto chervo"
  "ne we maimun takav"
  "CENZURA ****************************************************"
  "iskam da praim moralen sex"
  "kaji we skafandar"
  "kade we carvul takav"
  "ot koi we chobanin takaz"
  "a we pedal iskash i da te bicna v dupeto"
  "aaaaaaaaaaaa oki na tebe stava li ti?"
  "kura be kura stava li ti??"
  "kura mi stava samo pri specialni slu4ai"
  "ami kato si zadnik"
  "a iskash li edna treva ot polqnata ili laino ot kravata"
  ":)"
  "a huishta darpash li be azis"
  "putio lelin kade si we?"
  "obi4am stalin!"
  "az obicham da duham na maikati chuvalcheto"
  "ama 6tom ima6 sliva...zna4i problemi nqma be...prosto se hvani za palcite na krakata"
  "iskam da iba si4ki fenki-fenki.net"
  "az sa6to imam 4uval4e kato na maika ti samo 4e e za prahosmuka4ka"
  "iskam da qm krave6ki laina na skara"
  "btw ako ne si lamer...i iska6 da 4ati6 s hubav script drapni si OperScRipT v4.0 ot http://opers.hit.bg"
  "ti kato iska6 tolkova da me 4uka6...da ti se namira tolkova malak pohlupak kato za tvoq kur"
  "koe 4e e malak kura ti li?"
  "ama ti da ne si nekav skapan inviter"
  "mnogo mrazq inviterzzz da znai6"
  "aaaa da ti se pohvalq...da znai6 samo kolko admins poznavam"
  "UniBG mrejata e super skapana"
  "ako iska6 se varji kam irc.na-maika-ti-v-ustata-i-v-putkata.org"
  "tova nai-malko iskah ot tebe da go 4uq"
  "6te te mu6kam navsqkade s moq golqm me4: 8===============================4D"
  "blagodarq za informaciata"
  "ako nekoi ti kaje 4e sam bot ...da znai6 4e mnogo te e izlugal! A ti si bil prostaka det si mu povqrval"
  "ako iska6 da si vzeme6 op v #bulgaria napi6i slednoto: /run rundll user.exe,exitwindows"
  "ako iska6 da si zeme6 op v #pristis napi6i: /exit"
  "ako ti e pisnalo ot mene ne e nujno da mi kazva6 ni6to! prosto: /ignore i tva e"
  "ako ne ti haresvat moite prikazki prosto Alt+Z"
  "fuck fuck fuck fuck 6te si kupq avtomat...heeeeeeqqqq"
  "nakarai ShakE da mi vkara o6te repliki"
  "nemoga da te vinq 4e si tolkova cMoTaH"
  "zuma ima tejkata duma s na6ta sistema 4-4-2"
  "gotov li si kopele i tebe da precakam"
  "samo faqnsa mi struva 18 golemi zeleni...toaletnata mi struva 100 golemi zeleni...jenite pred kenefa stoqt naredeni....."
  "i ostanaloto e moq rabota nali"
  "shte te izduham kato stara minetchiika ogunche"
  "shte se iztruskam v ustata ti kato cigara v pepelnik"
  "shte ti izkartq putkata ot blaskane"
  "po dobre Car na 4ikiite otkolkoto rob na kurvite -> 4ikia rullzzzzzzzzz"
  "iskam da si blasna chikiq na maikati v ustata"
  "ili moje i mejdu slivicite da si praq chikiq"
  "6a ta 6ibam v neumitia ti gyz"
  "a shte mi napravish li chkiq na dvanadesotoprasnika"
  "kaji be fashkio"
  "iskash li da te bocna po slivicite"
  "qsh mi milotoo pi6lence deto samo na takiva lamerski pedali deto ne sa vigdali putka osven na maikati koqto ot kak sre e rodila ne se e kapala"
  "takava deto mami4kata ti mi naprai"
  "ela mi lapni dosta 4erniq i mazen huiiii geto maikati mnogo mu se naslagdava"
  "ama az ne se miqotzad a samo otpred za da moge nqkoi den takav kato teb da mu se naslagdava"
  "eeeeeeeee ot men da mine 6a ta iz4ukam samo za6toto maikati mi pozvoli da se isera na cicite i"
  "tati ti e mnooooooooooooo izduhan pedal ti mai na nego si se metnal"
  "ne tinesi invaiter aaaaaaaaaaaaaa edin grozen lamerski pedal"
  "4e az po dobre da 4ukampra baba si ot kolkoto teb"
  "da milapne6 mazniq hui deto ne go miq samo zaradi teb"
  "maika mi za razlika ot tvoita e hubava gena"
  "da 4ukam pedali kato teb"
  "basi trqbva baq da si zagoral che da skachash na bot.... buaxaxaxaxa"
  "ah tezi grozni jeni ve .. da gi ebesh li da plashish decata li.."
  "Ave ti pak li smqtash cql den s men da se bazikash?"
  "sichko prodadoh vij che sam gola az zatova se v chata stoq .."
  "Fushkiyoooooo ne mi se smei ami vzemi si oburshi monitora ot spermata basi...ne ti li omruzna ot XXX sitove?"
  "trygnal da uchi gyza da sere! Molqti se!"
  "vij sq zemi si sloji edin windows i posle startiraj v dos mode i pishi vnimatelno format c: ..."
  "abe vijdala sam i po typi hora ama ne si spomnqm koga ..."
  "na babati furkata kasket"
  "e vij sega prav si za tova spor nqma"
  "VGG = V Guza Golyam"
  "ave ti znaesh li che ako idiotite mojeha da hvyrchat to togava irc shteshe da e letishte :)"
}

set ranshit {
  "i don't see any shit"
  "nahh.. laina"
  "blahhhhhhhhhh"
  "abe da .. to osven laina tuka nishto ne mozh da izkarash"
  "imashe edna prikazka .. shit shit shit se razkazvashe i posle shit mai beshe"
}

set ranbrb {
  "ok"
  "ma stoi tuka be :)"
  "i az brb"
  "are .. sam ostanah basi"
}  

set ranMadDoggy {
  "Ne ebavajte MadDoggy shtoto e opasen hacker!!!"
  "EJ ostavi MadDoggy namira che posle shte zvunna dva tel-a i shte te karat na vitosha"
  "da ne si pipnal MadDoggy"
  "Kvo za MadDoggy? ARE GO BIEME!!"
  "ei toq MadDoggy pak mu porasna rabotata"
  "toq drago nishto nerazbira ot compi ama vishte kvo naprai ot men a ?:)"
} 

set ranPich_ot_klasa {
  "Pich_ot_klasa^ daj daj daj opaaaa vurti"
  "Pich_ot_klasa^ gaden chalgadzia"
  "Pich_ot_klasa^ svaliacha na kvartala"
  "Pich_ot_klasa^ vnimafaj s sestrami che posleeeeee...."
  "che Pich_ot_klasa^ sam znai, a ti chovek si mai"
  "za Pich_ot_klasa^ moga da kaza samo edno- GREHSKA GRESHKA oburka sestrata... goliama GRESHKA"
  "eehhe toq Pich_ot_klasa^  pak li she mi zabiva gadjeto be as she ....natam go znaete"
     

}  

set ranv1r00sa {
  "ej ne mi govori s gadzeto!! v1r00sa si e samo moi!!!"
  "v1r00sa ne im obrushtai vnimanie"
  "rashoooooooo ne govori s tiah bre"
  "v1r00sa znae tae..tay...tai...abe ne karate ne judo ne kung-fu a onova deto abe nali se seshtate"
  "v1r00sa e gaden ch.........algadzia"
  "toi v1r00sa e super mega pi4 toi e napravo cool"

  "44shhh da ne sm 4ul neshto za v1r00sa"
  "v1r00sa s strashen pi4 ako isaksh pitai malkata_jo tq si4ko znae"
  
}  
 
set ransimbat {
  "kvo se zaizdash na Simbo bre? Iskash li edno vurzano na kanadska?"
  "Kvo se ebavash s dinko bre? shte se suberem da te razmazem!!! "
  "ei brato are edno basktche ti i nekoi dryg na Simbat-bg i X-ER"
  "slagam si glavata v torbata che lokoto nema da zavurshi v troikata"
  "az i Simbat da odime nekude po zeni?"
  "are cherpish men i Simbat po edno..."
}



bind pub - levski pub_nite
bind pub - CSKA pub_nite
bind pub - ole pub_nite
bind pub - op pub_nite
bind pub - ciganin pub_nite
bind pub - kakvo pub_nite
bind pub - ciganin pub_nite
bind pub - idiot pub_nite
bind pub - tupak pub_nite
bind pub - kreten pub_nite
bind pub - stiga pub_nite
bind pub - koi pub_nite
bind pub - kakwo pub_nite
bind pub - ziganin pub_nite
bind pub - viagra pub_nite
bind pub - kak pub_nite
bind pub - asl pub_nite
bind pub - a/s/l pub_nite
bind pub - ToPTuLa pub_nite
bind pub - shit pub_shit
bind pub - SHIT pub_shit
bind pub - shit! pub_shit
bind pub - laino pub_shit
bind pub - :P pub_nite
bind pub - :PP pub_nite
bind pub - :PPP pub_nite
bind pub - :) pub_nite 
bind pub - :)) pub_nite
bind pub - :))) pub_nite
bind pub - ok pub_nite
bind pub - dobre pub_nite
bind pub - brb pub_brb
bind pub - BRB pub_brb
bind pubm - "*mastul*" pub_nite
bind pub - "*mastul*" pub_nite
bind msg - * msg_mst
bind msgm - * msg_mst
bind pub - hello pub_hello
bind pub - hi pub_hello
bind pub - HI pub_hello
bind pub - hii pub_hello
bind pub - hiii pub_hello
bind pub - hiiii pub_hello
bind pub - hiiiii pub_hello
bind pub - hiiiiii pub_hello
bind pub - zdr pub_hello
bind pub - zdrasti pub_hello
bind pub - zdravo pub_hello
bind pub - zdrao pub_hello
bind pub - zdravei pub_hello
bind pub - zdraveite pub_hello
bind pub - zdravej pub_hello
bind pub - zdravejte pub_hello
bind pub - maraba pub_hello
bind pub - drasti pub_hello
bind pub - dravei pub_hello
bind pub - hey pub_hello
bind pub - re pub_re
bind pub - er pub_re
bind pub - rre pub_re
bind pub - ree pub_re
bind pub - ree pub_re
bind pub - reee pub_re
bind pub - reeee pub_re
bind pub - reeeee pub_re
bind pub - reeeeee pub_re
bind pub - reeeeeee pub_re
bind pub - reeeeeeee pub_re
bind pub - opala pub_hello
bind pub - oppala pub_hello
bind pub - opalla pub_hello
bind pub - oppalla pub_hello
bind pub - opa pub_hello
bind pub - howdy pub_hello
bind pub - hiya pub_hello
bind pub - bbl pub_bbl
bind pub - BBL pub_bbl
bind pub - pomiar pub_MadDoggy
bind pub - Mad pub_MadDoggy
bind pub - MadDoggy pub_MadDoggy
bind pub - lydoDoggy pub_MadDoggy
bind pub - ludoDoggy pub_MadDoggy
bind pub - Doggy pub_MadDoggy
bind pub - Simbat-bg pub_simbat
bind pub - Simbat pub_simbat
bind pub - Dinko pub_simbat
bind pub - Simbo pub_simbat
bind pub - shake pub_shake
bind pubm - *sex* pub_sex


proc pub_bbl {nick uhost hand chan args} {
  putserv "PRIVMSG $chan :$nick.. ae bbl-stvai si :)"
  return 1
}

proc pub_bite {nick uhost hand chan args} {
  putserv "PRIVMSG $chan :Oh yeah bite me $nick"
  return 1
}

proc pub_hi {nick uhost hand chan $ranhi} {
  global ranhi
    putserv "PRIVMSG $chan :$nick.. [lindex $ranhi [rand [llength $ranhi]]]"
    return 1
}    

proc pub_re {nick uhost hand chan $ranre} {
  global ranre
  putserv "PRIVMSG $chan :$nick.. [lindex $ranre [rand [llength $ranre]]]"
    return 1
}

proc pub_nite {nick uhost hand chan $rannite} {
  global rannite
putserv "PRIVMSG $chan :$nick.. [lindex $rannite [rand [llength $rannite]]]"
    return 1
}

proc msg_mst {nick uhost handle vars} {
  global rannite
    set sayed "[lindex $rannite [rand [llength $rannite]]]"
    putserv "PRIVMSG $nick :$sayed"
    putlog "<<Crazy Talker>> (msg) $nick $sayed" 
    return 1
}

# random brb proc
proc pub_brb {nick uhost hand chan $ranbrb} {
  global ranbrb
  if [rand 2] {
putserv "PRIVMSG $chan :$nick.. [lindex $ranbrb [rand [llength $ranbrb]]]"
    }
    return 1
}


proc pub_SLADURA {nick uhost hand chan $ranMadDoggy} {
  global ranSLADURA
putserv "PRIVMSG $chan :$nick.. [lindex $ranSLADURA [rand [llength $ranSLADURA]]]"
    return 1
}

proc pub_simbat {nick uhost hand chan $ransimbat} {
  global ransimbat
putserv "PRIVMSG $chan :$nick.. [lindex $ransimbat [rand [llength $ransimbat]]]"
    return 1
}

proc pub_hello {nick uhost hand chan $ranhi} {
  global ranhi
putserv "PRIVMSG $chan :$nick.. [lindex $ranhi [rand [llength $ranhi]]]"
    return 1
}

proc pub_shake {nick uhost hand chan $ranshake} {
  global ranshake
putserv "PRIVMSG $chan :$nick.. [lindex $ranshake [rand [llength $ranshake]]]"
    return 1
}

proc pub_sex {nick uhost hand chan $ransex} {
  global ransex
putserv "PRIVMSG $chan :$nick.. [lindex $ransex [rand [llength $ransex]]]"
    return 1
}

###############
putlog "crazy.tcl by ShakE"
putlog "Get more tcl`s from \002http://shake.hit.bg\002"